# Generated by Django 4.0.3 on 2022-03-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('salary', models.FloatField(verbose_name='salary')),
                ('sphere', models.CharField(choices=[('it', 'Information Technologies'), ('edu', 'Education or Science'), ('healthcare', 'Healthcare'), ('culture', 'Culture'), ('sport', 'Sport'), ('managerial', 'Administrative, managerial and office activities'), ('economy', 'Economy')], max_length=100, verbose_name='sphere')),
            ],
            options={
                'db_table': 'vacancies',
            },
        ),
    ]
