# Generated by Django 4.0.3 on 2022-03-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='sphere',
            field=models.CharField(choices=[('IT', 'Information Technologies'), ('EDU', 'Education or Science'), ('HEALTH', 'Healthcare'), ('CULTURE', 'Culture'), ('SPORT', 'Sport'), ('MANAGERIAL', 'Administrative, managerial and office activities'), ('ECONOMY', 'Economy')], max_length=100, verbose_name='sphere'),
        ),
    ]
